transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlog -vlog01compat -work work +incdir+/home/strea/iot/product/production/ip/edge_detect {/home/strea/iot/product/production/ip/edge_detect/altera_edge_detector.v}
vlog -vlog01compat -work work +incdir+/home/strea/iot/product/production/ip/debounce {/home/strea/iot/product/production/ip/debounce/debounce.v}
vlog -vlog01compat -work work +incdir+/home/strea/iot/product/production/ip/altsource_probe {/home/strea/iot/product/production/ip/altsource_probe/hps_reset.v}
vlog -vlog01compat -work work +incdir+/home/strea/iot/product/production {/home/strea/iot/product/production/pwm.v}
vlog -vlog01compat -work work +incdir+/home/strea/iot/product/production {/home/strea/iot/product/production/DE10_NANO_SoC_GHRD.v}
vlib soc_system
vmap soc_system soc_system
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis {/home/strea/iot/product/production/soc_system/synthesis/soc_system.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_4.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_4_avalon_st_adapter.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_3.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_2.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_1.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_0.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_sysid_qsys.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_sensor_pio.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_onchip_memory.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_nios_cpu_pio.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_nios2_cpu.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_nios2_cpu_cpu.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_nios2_cpu_cpu_debug_slave_tck.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_nios2_cpu_cpu_debug_slave_sysclk.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_nios2_cpu_cpu_debug_slave_wrapper.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_nios2_cpu_cpu_test_bench.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_mm_bridge.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_led_pio.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_jtag_uart_1.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_jtag_uart.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_i2c.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_i2c_csr.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_i2c_clk_cnt.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_i2c_condt_det.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_i2c_condt_gen.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_i2c_fifo.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_i2c_mstfsm.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_i2c_rxshifter.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_i2c_txshifter.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_i2c_spksupp.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_i2c_txout.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_hps_0.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_hps_0_hps_io.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/hps_sdram.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_mem_if_hhp_qseq_synth_top.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/hps_sdram_p0_acv_ldc.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/hps_sdram_p0_acv_hard_addr_cmd_pads.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/hps_sdram_p0_clock_pair_generator.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/hps_sdram_p0_acv_hard_io_pads.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/hps_sdram_p0_altdqdqs.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/hps_sdram_p0_acv_hard_memphy.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/hps_sdram_p0_generic_ddio.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_f2sdram_only_master.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_packets_to_master.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_st_packets_to_bytes.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_st_bytes_to_packets.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_st_jtag_interface.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_jtag_dc_streaming.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_jtag_sld_node.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_jtag_streaming.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_st_clock_crosser.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_std_synchronizer_nocut.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_st_idle_remover.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_st_idle_inserter.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_dipsw_pio.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_button_pio.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/MyPIO.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/interrupt_latency_counter.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/irq_detector.v}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/state_machine_counter.v}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_irq_mapper_003.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_irq_mapper_002.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_irq_mapper_001.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_irq_mapper.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_4_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_merlin_width_adapter.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_merlin_address_alignment.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_4_rsp_mux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_4_cmd_mux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_4_cmd_demux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_4_router_001.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_4_router.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_merlin_master_agent.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_merlin_master_translator.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_3_rsp_mux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_3_rsp_demux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_3_cmd_mux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_3_cmd_demux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_merlin_traffic_limiter.sv}
vlog -vlog01compat -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_avalon_st_pipeline_base.v}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_3_router_001.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_3_router.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_merlin_axi_slave_ni.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_2_rsp_mux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_2_rsp_demux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_2_cmd_mux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_2_cmd_demux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_2_router_002.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_2_router.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_rsp_mux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_rsp_demux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_cmd_mux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_cmd_demux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_merlin_burst_adapter_13_1.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_router_002.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_1_router.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_merlin_axi_master_ni.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_rsp_mux_001.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_rsp_demux_001.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_cmd_mux_001.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_cmd_demux_001.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_router_003.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_router_002.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_router_001.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_mm_interconnect_0_router.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/hps_sdram_p0.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_mem_if_oct_cyclonev.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_mem_if_hard_memory_controller_top_cyclonev.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altdq_dqs2_acv_connect_to_hard_phy_cyclonev.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/altera_mem_if_dll_cyclonev.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/hps_sdram_pll.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_hps_0_hps_io_border.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_hps_0_fpga_interfaces.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_f2sdram_only_master_p2b_adapter.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_f2sdram_only_master_b2p_adapter.sv}
vlog -sv -work soc_system +incdir+/home/strea/iot/product/production/soc_system/synthesis/submodules {/home/strea/iot/product/production/soc_system/synthesis/submodules/soc_system_f2sdram_only_master_timing_adt.sv}

